
export const PRODUCT_DETAILS_SIZE_ARRAY = [
    'OS',
    "ONE SIZE",
    'XS',
    'S',
    'M',
    'L',
    'XL',
    '2XL',
    '3XL',
    '4XL',
    '5XL',
];
export const PRODUCT_DETAILS_SIZE_TABLE_COLUMNS = [
    { title: "", dataIndex: "measurement", key: "2", },
    { title: "S", dataIndex: "S", key: "3", },
    { title: "M", dataIndex: "M", key: "4", },
    { title: "L", dataIndex: "L", key: "5", },
    { title: "XL", dataIndex: "XL", key: "6", },
    { title: "2XL", dataIndex: "2XL", key: "7", },
    { title: "3XL", dataIndex: "3XL", key: "8", },
    { title: "4XL", dataIndex: "4XL", key: "9", },
    { title: "5XL", dataIndex: "5XL", key: "10", },
];
export const PRODUCT_DETAILS_SIZE_TABLE_DATA = [
    {
        key: "1",
        measurement: "Width",
        "S": "10-20",
        "M": "20-30",
        "L": "40-50",
        "XL": "50-60",
        "2XL": "60-70",
        "3XL": "70-80",
        "4XL": "80-90",
        "5XL": "90-100",
    },
    {
        key: "2",
        measurement: "Length",
        "S": "10-20",
        "M": "20-30",
        "L": "40-50",
        "XL": "50-60",
        "2XL": "60-70",
        "3XL": "70-80",
        "4XL": "80-90",
        "5XL": "90-100",
    },
];

export const HEADER_NAV_ITEMS = [
    {
        id: "services",
        key: "services",
        name: "Our Services",
        parent_product_category_id: null,
        parent_product_category_key: null,
        sort_order: 1,
        children: [
            {
                id: "what-we-do",
                key: "what-we-do",
                name: "What we do",
                url: "/WhatWeDo",
                parent_product_category_id: "services",
                parent_product_category_key: "services",
                sort_order: 1,
                children: [],
            },
            {
                id: "creative-and-production",
                key: "creative-and-production",
                name: "Creative & Production",
                url: "/Production",
                parent_product_category_id: "services",
                parent_product_category_key: "services",
                sort_order: 1,
                children: [],
            },
            {
                id: "warehouse-and-distribution",
                key: "warehouse-and-distribution",
                name: "Warehouse & Distribution",
                url: "/Warehouse",
                parent_product_category_id: "services",
                parent_product_category_key: "services",
                sort_order: 1,
                children: [],
            },

            {
                id: "custom-portal",
                key: "custom-portal",
                name: "Custom Portal",
                url: "/CustomPortal",
                parent_product_category_id: "services",
                parent_product_category_key: "services",
                sort_order: 1,
                children: [],
            },
            {
                id: "why-merch",
                key: "why-merch",
                name: "Why Merch",
                url: "/WhyMerch",
                parent_product_category_id: "services",
                parent_product_category_key: "services",
                sort_order: 1,
                children: [],
            },
        ],
    },
    {
        id: "products",
        key: "products",
        name: "Products",
        parent_product_category_id: null,
        parent_product_category_key: null,
        sort_order: 1,
        children: [
            {
                id: "all-merch",
                key: "all-merch",
                name: "All Merch",
                url: "/AllMerch",
                parent_product_category_id: "products",
                parent_product_category_key: "products",
                sort_order: 1,
                children: [],
            },
            {
                id: "custom-packs",
                key: "custom-packs",
                name: "Custom Packs",
                url: "/CustomPacks",
                parent_product_category_id: "products",
                parent_product_category_key: "products",
                sort_order: 1,
                children: [],
            },
            {
                id: "curated-packs",
                key: "-packs",
                name: "Curated Packs",
                url: "/CuratedPacks",
                parent_product_category_id: "products",
                parent_product_category_key: "products",
                sort_order: 1,
                children: [],
            },
        ],
    },
    {
        id: "info",
        key: "Info",
        name: "Info",
        parent_product_category_id: null,
        parent_product_category_key: null,
        sort_order: 1,
        children: [
            {
                id: "who-we-are",
                key: "who-we-are",
                name: "Who we are",
                url: "/WhoWeAre",
                parent_product_category_id: "info",
                parent_product_category_key: "info",
                sort_order: 1,
                children: [],
            },
            {
                id: "sustainability ",
                key: "sustainability",
                name: "Sustainability",
                url: "/Sustainability",
                parent_product_category_id: "info",
                parent_product_category_key: "info",
                sort_order: 1,
                children: [],
            },
            {
                id: "case-studies",
                key: "case-studies",
                name: "Case Studies",
                url: "/caseStudies",
                parent_product_category_id: "info",
                parent_product_category_key: "info",
                sort_order: 1,
                children: [],
            },
            {
                id: "blog",
                key: "blog",
                name: "Blog",
                url: "/Blog",
                parent_product_category_id: "info ",
                parent_product_category_key: "info",
                sort_order: 1,
                children: [],
            },
        ],
    },
];

export const ENQUIRY_PRODUCT_TYPES_SEO_DATA = {
    "all-merch": {
        "title" : "Create Custom Merchandise for Brands in Australia",
        "description": "We've supplied custom merch for many brands in Australia, including Target, ZIP, and Boost Juice. Design custom merchandise to promote your brand with us.",
    },
    "custom-pack": {
        "title" : "Building Custom Merchandise Pack",
        "description": "Build your custom merchandise pack with MyMerch today. Add merch to your enquiry, select the packaging you want and your order quantity to get a quote.",
    },
    "curated-pack": {
        "title" : "Curated Merchandise Packs",
        "description": "We have a variety of curated merch pack options for every need and requirement. Simply pick one and indicate the order quantity to receive your quote.",
    },
    
};