// "use client";
import "./globals.css";
// import type { Metadata } from 'next'
import { Inter } from "next/font/google";
import Footer from "@/common/Footer";
import { Layout } from "antd";
// import configureStore from "@/utilities/configureStore";
// import { PersistGate } from "redux-persist/integration/react";
// import { Provider } from "react-redux";
// import ReduxProvider from './provider';
// import { ConfigProvider } from "antd";
import "@/scss/main.scss";
import LayoutPrimary from "./LayoutPrimary";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
// const { store } = configureStore();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Provider store={store}> */}
        {/* <ReduxProvider> */}
        {/* <PersistGate loading={null} persistor={persistor}> */}
        {/* <ConfigProvider
          theme={{
            token: {
              fontFamily: '"Neutra Text"',
            },
          }}
        > */}
        {/* <App>
            <Routes />
          </App> */}
        <Layout>
          <LayoutPrimary>{children}</LayoutPrimary>
          <Footer />
        </Layout>

        {/* </ConfigProvider> */}

        {/* </PersistGate> */}
        {/* </ReduxProvider> */}
        {/* </Provider> */}
      </body>
    </html>
  );
}
